//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JedinicnoTestiranje
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Artikli> Artikli { get; set; }
        public virtual DbSet<Korisnik> Korisnik { get; set; }
        public virtual DbSet<Nacin_placanja> Nacin_placanja { get; set; }
        public virtual DbSet<Racun> Racun { get; set; }
        public virtual DbSet<Rezervacija> Rezervacija { get; set; }
        public virtual DbSet<Status_korisnika> Status_korisnika { get; set; }
        public virtual DbSet<Status_racuna> Status_racuna { get; set; }
        public virtual DbSet<Stavke_racuna> Stavke_racuna { get; set; }
        public virtual DbSet<Tip> Tip { get; set; }
        public virtual DbSet<Tjedni_raspored> Tjedni_raspored { get; set; }
        public virtual DbSet<Uloga> Uloga { get; set; }
    }
}
