//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JedinicnoTestiranje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tjedni_raspored
    {
        public int ID { get; set; }
        public System.DateTime Datum_od { get; set; }
        public System.DateTime Datum_do { get; set; }
        public string Pon { get; set; }
        public string Uto { get; set; }
        public string Sri { get; set; }
        public string Cet { get; set; }
        public string Pet { get; set; }
        public string Sub { get; set; }
        public string Ned { get; set; }
        public int Broj_sati { get; set; }
        public int vk_korisnik { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
    }
}
