//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NjamiNjam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Racun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Racun()
        {
            this.Stavke_racuna = new HashSet<Stavke_racuna>();
        }
    
        public int ID { get; set; }
        public int Broj_stola { get; set; }
        public System.DateTime Vrijeme { get; set; }
        public decimal Cijena { get; set; }
        public int Popust { get; set; }
        public int vk_korisnik { get; set; }
        public int vk_nacin { get; set; }
        public int vk_status { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        public virtual Nacin_placanja Nacin_placanja { get; set; }
        public virtual Status_racuna Status_racuna { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stavke_racuna> Stavke_racuna { get; set; }
    }
}
