//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NjamiNjam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezervacija
    {
        public int ID { get; set; }
        public int Broj_stola { get; set; }
        public int Broj_gostiju { get; set; }
        public System.DateTime Datum { get; set; }
        public string Opis { get; set; }
        public int vk_korisnik { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
    }
}
